=== TypingTobii/cer-tool/config/config.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "filenames": {
            "type": "object",
            "properties": {
                "edit_feedback_file": {
                    "type": "string"
                },
                "feedback_filename_prefix": {
                    "type": "string"
                },
                "tmp_folder": {
                    "type": "string"
                }
            },
            "required": [
                "edit_feedback_file",
                "feedback_filename_prefix",
                "tmp_folder"
            ]
        },
        "initials": {
            "type": "string"
        },
        "moodle": {
            "type": "object",
            "properties": {
                "feedback_footer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "file_upload_limit_bytes": {
                    "type": "integer"
                },
                "submission_keyword": {
                    "type": "string"
                }
            },
            "required": [
                "feedback_footer",
                "file_upload_limit_bytes",
                "submission_keyword"
            ]
        },
        "pex": {
            "type": "object",
            "properties": {
                "docker_group_name": {
                    "type": "string"
                },
                "text_divider": {
                    "type": "string"
                },
                "html_magic_comment": {
                    "type": "string"
                }
            },
            "required": [
                "docker_group_name",
                "text_divider",
                "html_magic_comment"
            ]
        },
        "verbose": {
            "type": "boolean"
        }
    },
    "required": [
        "filenames",
        "initials",
        "moodle",
        "pex"
    ]
}

=== TypingTobii/cer-tool/config/config.json
{
    "filenames": {
        "edit_feedback_file": "__CER_TOOL_TEMP_COMMENT__.txt",
        "feedback_filename_prefix": "Feedback",
        "tmp_folder": "__CER_TOOL_TEMP_FOLDER{}__"
    },
    "initials": "???",
    "moodle": {
        "feedback_footer": [
            "<strong>- {}</strong>"
        ],
        "file_upload_limit_bytes": 24999500,
        "submission_keyword": "assignsubmission_file"
    },
    "pex": {
        "docker_group_name": "cer-tool",
        "html_magic_comment": "<!--%%%-->",
        "text_divider": "%"
    }
}
